services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: no
    volumes:
      - /media/mhmdali102/KINGSTON/Books:/books
      - ./data:/kavita/config
    environment:
      - TZ=Asia/Beirut
    ports:
      - "1234:5000"
