version: "3"

networks:
  npm_default:
    external: true

services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: no
    volumes:
      - ./books:/books
      - ./data:/kavita/config
    environment:
      - TZ=Asia/Beirut
    networks:
      - npm_default
    ports:
      - "1234:5000"
