version: "3.5"

services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: no
    ports:
      - 8484:8080
      - 8443:8443
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
