services:
  qbittorrent:
    container_name: qb
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qb:/config
      - ./downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: no

  qui:
    container_name: qui
    image: ghcr.io/autobrr/qui:latest
    depends_on:
      - qb
    restart: no
    ports:
      - 7476:7476
    volumes:
      - ./qui:/config
