---
version: "2.1"

networks:
  npm_default:
    external: true

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: no
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Beirut
    volumes:
      - ./config:/config
    networks:
      - npm_default
    ports:
      - 8443:8443
