services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: no
    ports:
      - "9925:9000"
    volumes:
      - ./data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Beirut
      - BASE_URL=https://localhost:9925
