version: "3.8"

services:
  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "7000:8080"
    volumes:
      - ./config.toml:/usr/src/app/config.toml:bind
      - ./data:/usr/src/app/db:bind
