services:
  odoo17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo17@2023
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: no
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2023
      - POSTGRES_DB=postgres
    restart: no
    volumes:
        - ./postgresql:/var/lib/postgresql/data
