services:
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    restart: no
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MyWordPressUser
      WORDPRESS_DB_PASSWORD: Pa$$5w0rD
      WORDPRESS_DB_NAME: MyWordPressDatabaseName
    volumes:
      - ./wordpress:/var/www/html
  db:
    container_name: wordpress_db
    image: mysql:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: MyR00tMySQLPa$$5w0rD
      MYSQL_DATABASE: MyWordPressDatabaseName
      MYSQL_USER: MyWordPressUser
      MYSQL_PASSWORD: Pa$$5w0rD
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
