services:
  ghost:
    image: ghost:5-alpine
    restart: no
    depends_on:
      - db
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: http://localhost:8080
      NODE_ENV: development
    volumes:
      - ./content:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/var/lib/mysql
