services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: no
    ports:
      - 8088:8080
    volumes:
      - ./trainingData:/usr/share/tesseract-ocr/4.00/tessdata
      - ./extraConfigs:/configs
      - ./customFiles:/customFiles/
