version: "3"

services:
  yaade:
    image: esperotech/yaade:latest
    container_name: yaade
    restart: no
    environment:
      - YAADE_ADMIN_USERNAME=admin
    ports:
      - 9339:9339
    volumes:
      - ./data:/app/data
