---
version: "3"

networks:
  npm_default:
    external: true

services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    restart: no
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Beirut
    volumes:
      - ./syncthing:/var/syncthing
    networks:
      - npm_default
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
