version: "3.3"

networks:
  npm_default:
    external: true

services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    restart: no
    networks:
      - npm_default
    ports:
      - 86:80
