version: "3.8"

networks:
  default:
    external: false

services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: no
    container_name: npm
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Beirut
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - default
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
